version: 0.3

phases:
  pre_build:
  commands:
    - cd /codebuild/output/src1008918221/src/
    - npm cache clean --force
    - echo "Installing dependencies into the node_modules/ directory"
    - npm install

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Compiling"
      - npm run build

artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
    - dist/**/*

# Specify additional settings if needed
# For example, environment variables, runtime settings, etc.
# environment:
#   variables:
#     KEY: "value"
# runtime:
#   nodejs:
#     version: 14
